package model;

public enum ProductCategory {
    BOOKS,
    ELECTRONICS,
    CLOTHES_AND_ACCESSORIES,
    FOOD_AND_DRINKS,
    STATIONERY,
    SPORTS,
    BEAUTY_PRODUCTS_AND_PERSONAL_CARE,
    TOYS_AND_GAMES
}
